server:
  port: 7001
  error:
    include-message: always
 
spring:
  application:
    name: product
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalSeconds: 5
    leaseExpirationDurationInSeconds: 5


logging:
  level:
    root: INFO
    com.psc.cloud.product: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG