
server:
  port: 7000
app:
  product:
    protocol: http
    host: localhost
    service: product
    port: 7001
  recommend:
    protocol: http
    host: localhost
    service: recommend
    port: 7002
  review:
    protocol: http
    host: localhost
    service: review
    port: 7003    

spring:
  application:
    name: composite

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalSeconds: 5
    leaseExpirationDurationInSeconds: 5

logging:
  level:
    root: INFO
    com.psc.cloud.composite: DEBUG    