spring:
  cloud:
    gateway:
      routes:
        - id: composite
          uri: lb://composite
          predicates:
            - Path=/composite/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/