spring:
  cloud:
    gateway:
      routes:
        - id: composite
          uri: lb://composite
          predicates:
            - Path=/composite/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/


logging:
  level:
    root: INFO
    com.psc.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE