server:
  port: 7003
  error:
    include-message: always
    
spring:
  application:
    name: review
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost/review-db
    username: user01
    password: user01
    hikari:
      initializationFailTimeout: 60000


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalSeconds: 5
    leaseExpirationDurationInSeconds: 5


logging:
  level: 
    root: INFO
    com.psc.cloud.review: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE          